# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transfers.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'transfers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftransfers.proto\"Q\n\x0fTransferRequest\x12\x17\n\x0f\x66rom_account_id\x18\x01 \x01(\x05\x12\x15\n\rto_account_id\x18\x02 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"L\n\x10TransferResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"a\n\x0cTransferItem\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x17\n\x0f\x66rom_account_id\x18\x02 \x01(\x05\x12\x15\n\rto_account_id\x18\x03 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\"7\n\x17TransferHistoryResponse\x12\x1c\n\x05items\x18\x01 \x03(\x0b\x32\r.TransferItem2|\n\x0fTransferService\x12\x33\n\x0cMakeTransfer\x12\x10.TransferRequest\x1a\x11.TransferResponse\x12\x34\n\nGetHistory\x12\x0c.UserRequest\x1a\x18.TransferHistoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transfers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSFERREQUEST']._serialized_start=19
  _globals['_TRANSFERREQUEST']._serialized_end=100
  _globals['_TRANSFERRESPONSE']._serialized_start=102
  _globals['_TRANSFERRESPONSE']._serialized_end=178
  _globals['_USERREQUEST']._serialized_start=180
  _globals['_USERREQUEST']._serialized_end=210
  _globals['_TRANSFERITEM']._serialized_start=212
  _globals['_TRANSFERITEM']._serialized_end=309
  _globals['_TRANSFERHISTORYRESPONSE']._serialized_start=311
  _globals['_TRANSFERHISTORYRESPONSE']._serialized_end=366
  _globals['_TRANSFERSERVICE']._serialized_start=368
  _globals['_TRANSFERSERVICE']._serialized_end=492
# @@protoc_insertion_point(module_scope)
