# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: accounts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'accounts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61\x63\x63ounts.proto\x12\x08\x61\x63\x63ounts\"7\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x01\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"7\n\x10\x41\x63\x63ountsResponse\x12#\n\x08\x61\x63\x63ounts\x18\x01 \x03(\x0b\x32\x11.accounts.Account\":\n\x14UpdateBalanceRequest\x12\x12\n\naccount_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\"_\n\x15UpdateBalanceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bnew_balance\x18\x02 \x01(\x01\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t2\xa6\x01\n\x0f\x41\x63\x63ountsService\x12\x41\n\x0cListAccounts\x12\x15.accounts.UserRequest\x1a\x1a.accounts.AccountsResponse\x12P\n\rUpdateBalance\x12\x1e.accounts.UpdateBalanceRequest\x1a\x1f.accounts.UpdateBalanceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'accounts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNT']._serialized_start=28
  _globals['_ACCOUNT']._serialized_end=83
  _globals['_USERREQUEST']._serialized_start=85
  _globals['_USERREQUEST']._serialized_end=115
  _globals['_ACCOUNTSRESPONSE']._serialized_start=117
  _globals['_ACCOUNTSRESPONSE']._serialized_end=172
  _globals['_UPDATEBALANCEREQUEST']._serialized_start=174
  _globals['_UPDATEBALANCEREQUEST']._serialized_end=232
  _globals['_UPDATEBALANCERESPONSE']._serialized_start=234
  _globals['_UPDATEBALANCERESPONSE']._serialized_end=329
  _globals['_ACCOUNTSSERVICE']._serialized_start=332
  _globals['_ACCOUNTSSERVICE']._serialized_end=498
# @@protoc_insertion_point(module_scope)
